// One-off build script (run with `node build-pages.js`) — NOT part of the
// deployed Worker. It rebrands the copied v2 frontend pages (PayLink →
// FreePay, old palette references → new one) and bundles them into
// src/pages.generated.js as plain JS string constants, which src/index.js
// then serves directly. Re-run this after editing anything in src/pages/raw.

const fs = require("fs");
const path = require("path");

const RAW_DIR = path.join(__dirname, "src", "pages", "raw");
const STYLE_PATH = path.join(__dirname, "src", "pages", "style.css");
const OUT_PATH = path.join(__dirname, "src", "pages.generated.js");

// Text replacements applied to every .html/.js source file.
const REPLACEMENTS = [
  [/PayLink Sync/g, "FreePay Sync"],
  [/Pay<span>Link<\/span>/g, "Free<span>Pay</span>"],
  [/PayLink/g, "FreePay"],
  [/paylink-sync\.apk/g, "freepay-sync.apk"],
  // old palette values used inline (outside CSS vars) -> new palette
  [/#ABA6D6/g, "#9FB3AA"],
  [/#C7C4E0/g, "#B9C6C0"],
  [/#A7ABC0/g, "#9FB3AA"],
  [/#8B7CF7/g, "#7C8CF0"],
  [/#1B1B2F/g, "#0B1120"],
  [/#181826/g, "#0B1120"],
];

function rebrand(content) {
  let out = content;
  for (const [pattern, replacement] of REPLACEMENTS) out = out.replace(pattern, replacement);
  return out;
}

function walk(dir, base) {
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  let files = [];
  for (const entry of entries) {
    const full = path.join(dir, entry.name);
    const rel = path.join(base, entry.name);
    if (entry.isDirectory()) files = files.concat(walk(full, rel));
    else files.push(rel);
  }
  return files;
}

const files = walk(RAW_DIR, "");
const PAGE_ROUTES = {}; // route path -> { varName, contentType }
const entries = [];

// index.html -> "/"
// pay.html   -> "/pay"
// app/x.html -> "/app/x.html" (keep the extension; internal links already use it)
// assets/*   -> "/assets/*"
for (const rel of files) {
  const relPosix = rel.split(path.sep).join("/");
  let route;
  if (relPosix === "index.html") route = "/";
  else if (relPosix === "pay.html") route = "/pay";
  else route = "/" + relPosix;

  const full = path.join(RAW_DIR, rel);
  let content = fs.readFileSync(full, "utf8");
  if (relPosix.endsWith(".html") || relPosix.endsWith(".js")) content = rebrand(content);

  const contentType = relPosix.endsWith(".css")
    ? "text/css; charset=UTF-8"
    : relPosix.endsWith(".js")
    ? "application/javascript; charset=UTF-8"
    : "text/html; charset=UTF-8";

  entries.push({ route, content, contentType });
}

// style.css lives outside raw/ (it's the newly authored design system)
entries.push({
  route: "/assets/style.css",
  content: fs.readFileSync(STYLE_PATH, "utf8"),
  contentType: "text/css; charset=UTF-8",
});

let out = "// AUTO-GENERATED by build-pages.js — do not edit by hand.\n";
out += "// Edit files under src/pages/raw/ or src/pages/style.css, then re-run `node build-pages.js`.\n\n";
out += "export const PAGES = {\n";
for (const e of entries) {
  out += `  ${JSON.stringify(e.route)}: { contentType: ${JSON.stringify(e.contentType)}, body: ${JSON.stringify(e.content)} },\n`;
}
out += "};\n";

fs.writeFileSync(OUT_PATH, out);
console.log(`Wrote ${entries.length} pages to ${OUT_PATH}`);
